version: '3.8'
services:
  mysql:
    image: mysql:8.0
    env_file: ./.env
    environment:
      - MYSQL_ROOT_USERNAME=$MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "3307:3306"

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=$MYSQL_ROOT_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQL_ROOT_PASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
