version: '3.8'
services:
  mysql:
    image: mysql:8.0
    env_file: ./.env
    environment:
      - MYSQL_ROOT_USERNAME=$MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT

  app:
    depends_on:
      - mysql
    restart: on-failure
    build: .
    image: test1
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=$MYSQL_ROOT_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQL_ROOT_PASSWORD
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
